# Generated by Django 4.1.2 on 2022-10-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lasttname', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=200)),
                ('code_postal', models.CharField(max_length=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
