# Generated by Django 4.1.2 on 2022-11-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='service-1.jpg', null=True, upload_to=''),
        ),
    ]
