# Generated by Django 4.1.2 on 2022-11-05 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demendeunappel',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.service'),
        ),
    ]
