# Generated by Django 4.1.2 on 2022-11-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_demendeunappel_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='demendeunappel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
