# Generated by Django 4.1.2 on 2022-11-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_demendeunappel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='demendeunappel',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='demendeunappel',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
