# Generated by Django 4.1.2 on 2022-11-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_demendeunappel_date_demendeunappel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demendeunappel',
            name='service',
        ),
    ]
