# Generated by Django 4.1.2 on 2022-11-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_demendeunappel_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demendeunappel',
            name='date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='demendeunappel',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
